"""train.py — supplier risk model, trained offline, served from Node.

    python ml/train.py                     # train, evaluate, write model.json
    python ml/train.py --no-write          # evaluate only

Reads ml/training-data.csv (see tools/export-training-data.js) and writes
ml/model.json — intercept, coefficients, featureNames, means, stds. That file is
committed and read by api/src/risk/score.js. Python never runs at serve time.

WHAT THE LABEL IS
    y = 1 means this supplier's invoices did NOT reach that period's GSTR-2B
    correct and on time. Everything downstream is a risk, so a high probability
    is a bad supplier and the bands read directly.

WHY THE FEATURES COME FROM EARLIER PERIODS
    Each row's features are computed over the periods BEFORE its label period.
    Filing late in period P is most of P's label, so features spanning P would
    let the model read the answer off its own input.

HONESTY
    The training corpus is SYNTHETIC - generated by tools/generate-fixtures.js
    from rules we wrote. The model therefore largely learns our own generator,
    and the metrics below are evidence about that generator, NOT evidence that
    the model works on real GST filings. Nothing here has seen a real portal.
"""

import argparse
import json
import pathlib
import sys

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import average_precision_score, classification_report, roc_auc_score
from sklearn.preprocessing import StandardScaler

HERE = pathlib.Path(__file__).resolve().parent

# The features named in the brief, in the order model.json will carry them.
REQUESTED_FEATURES = [
    "filed_ratio_6m",
    "mean_days_late",
    "max_days_late",
    "mismatch_rate",
    "amendment_rate",
    "periods_observed",
    "gstr3b_filed_ratio",
]

# The last label period is never trained on. With five label periods a single
# holdout is ~40 rows, so leave-one-period-out across all five is reported too —
# one 40-row fold is not enough to tell two scorers apart.
HOLDOUT_PERIOD = "2026-07"

BAND_LOW = 0.15
BAND_HIGH = 0.40


def rule(title):
    print(f"\n{title}\n{'-' * len(title)}")


def load(path):
    frame = pd.read_csv(path)
    missing = [name for name in REQUESTED_FEATURES if name not in frame.columns]
    if missing:
        sys.exit(f"training data is missing columns: {', '.join(missing)}")
    return frame


def describe_missing(frame):
    """Explicit handling for features that are absent or carry no signal.

    Three distinct cases, and they are NOT the same thing:

      all-missing    the column is empty for every row. Nothing can be learned
                     and standardising it would divide by a zero std.
      zero-variance  present but identical on every row. Same problem: the
                     coefficient is meaningless and the scaler blows up.
      partly missing usable. Imputed to the TRAINING mean, which after
                     standardisation is exactly 0 — the feature then contributes
                     nothing for the rows where it is unknown, rather than
                     contributing a fabricated zero.

    Dropped features stay OUT of model.json entirely, so score.js cannot be fed
    a coefficient nobody estimated.
    """
    usable, dropped = [], []
    for name in REQUESTED_FEATURES:
        column = frame[name]
        if column.isna().all():
            dropped.append(
                (name, "no value in any row - not present in the ingested data", None)
            )
        elif column.dropna().nunique() <= 1:
            value = float(column.dropna().iloc[0])
            # The constant is recorded, not just described. Serving needs it: a
            # supplier whose value for a dropped feature differs from the one the
            # corpus always had is OUTSIDE what this model was fitted on, and
            # api/src/risk/score.js falls back to the heuristic for them rather
            # than scoring a pattern it has never seen. Held-out metrics cannot
            # catch that - the holdout has no such supplier either.
            dropped.append(
                (name, f"identical ({value:g}) on every row - no signal to learn from", value)
            )
        else:
            usable.append(name)
    return usable, dropped


def fit(train, features):
    """Standardise on the TRAINING fold only, then fit. Returns the pieces
    model.json needs plus the fitted objects."""
    raw = train[features].astype(float)
    means = raw.mean()
    # Imputation uses the training mean so a missing value standardises to 0.
    filled = raw.fillna(means)

    scaler = StandardScaler().fit(filled)
    model = LogisticRegression(
        # 21.5% positives. Balanced weighting stops the model from getting a
        # good-looking accuracy by calling everyone reliable — which is the one
        # failure mode this product cannot afford.
        class_weight="balanced",
        max_iter=1000,
    ).fit(scaler.transform(filled), train["label"])
    return model, scaler, means


def probabilities(model, scaler, means, frame, features):
    filled = frame[features].astype(float).fillna(means)
    return model.predict_proba(scaler.transform(filled))[:, 1]


def compare(name, y_true, model_scores, heuristic_scores):
    """Both scorers on the same rows. AUC and average precision are RANKING
    measures, which is what this is actually for - the screen is a ranked chase
    list, not a yes/no classifier."""
    if len(set(y_true)) < 2:
        print(f"  {name}: only one class present, nothing to measure")
        return None, None

    model_auc = roc_auc_score(y_true, model_scores)
    heuristic_auc = roc_auc_score(y_true, heuristic_scores)
    model_ap = average_precision_score(y_true, model_scores)
    heuristic_ap = average_precision_score(y_true, heuristic_scores)

    print(f"  {name}  (n={len(y_true)}, positives={int(sum(y_true))})")
    print(f"    {'':22}{'ROC AUC':>10}{'Avg prec':>12}")
    print(f"    {'logistic regression':22}{model_auc:>10.3f}{model_ap:>12.3f}")
    print(f"    {'phase 7 heuristic':22}{heuristic_auc:>10.3f}{heuristic_ap:>12.3f}")
    return (model_auc, heuristic_auc), (model_ap, heuristic_ap)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default=str(HERE / "training-data.csv"))
    parser.add_argument("--out", default=str(HERE / "model.json"))
    parser.add_argument("--no-write", action="store_true")
    args = parser.parse_args()

    frame = load(args.data)

    rule("Training data")
    periods = sorted(frame["tax_period"].unique())
    print(f"  rows          {len(frame)}")
    print(f"  suppliers     {frame['gstin'].nunique()}")
    print(f"  label periods {', '.join(periods)}")
    print(f"  positives     {int(frame['label'].sum())} ({frame['label'].mean() * 100:.1f}%)")
    print("  SYNTHETIC - generated by tools/generate-fixtures.js from rules we wrote.")
    print("  Metrics below describe that generator, not real GST filings.")

    features, dropped = describe_missing(frame)

    rule("Features")
    for name in REQUESTED_FEATURES:
        if name in features:
            column = frame[name]
            gap = f", {int(column.isna().sum())} missing" if column.isna().any() else ""
            print(f"  keep  {name:20} {column.dropna().nunique()} distinct values{gap}")
    for name, why, _constant in dropped:
        print(f"  DROP  {name:20} {why}")
    if dropped:
        print("\n  Dropped features are excluded from model.json rather than kept at a")
        print("  zero coefficient, so nothing downstream can read a weight nobody fitted.")
    if not features:
        sys.exit("every requested feature was dropped - nothing to train on")

    # --- leave-one-period-out ------------------------------------------------
    #
    # Grouped by PERIOD, not by row. A random split would put the same supplier's
    # March and April rows on both sides, and their features overlap heavily —
    # the score would be measuring memory of that supplier, not prediction.
    rule("Leave-one-period-out cross-validation")
    oof = np.full(len(frame), np.nan)
    for period in periods:
        is_test = frame["tax_period"] == period
        train, test = frame[~is_test], frame[is_test]
        if train["label"].nunique() < 2:
            continue
        model, scaler, means = fit(train, features)
        oof[is_test.to_numpy()] = probabilities(model, scaler, means, test, features)

    scored = ~np.isnan(oof)
    cv_auc, cv_ap = compare(
        "all folds pooled",
        frame.loc[scored, "label"].to_numpy(),
        oof[scored],
        frame.loc[scored, "heuristic_score"].to_numpy(),
    )

    # --- single held-out period ---------------------------------------------
    rule(f"Held-out period {HOLDOUT_PERIOD} (never trained on)")
    is_holdout = frame["tax_period"] == HOLDOUT_PERIOD
    train, holdout = frame[~is_holdout], frame[is_holdout]
    model, scaler, means = fit(train, features)
    holdout_probability = probabilities(model, scaler, means, holdout, features)

    print(f"  trained on {len(train)} rows, tested on {len(holdout)}")
    ho_auc, ho_ap = compare(
        HOLDOUT_PERIOD,
        holdout["label"].to_numpy(),
        holdout_probability,
        holdout["heuristic_score"].to_numpy(),
    )

    print(f"\n  Classification report at the HIGH band threshold ({BAND_HIGH}):")
    predicted = (holdout_probability > BAND_HIGH).astype(int)
    print(
        "\n".join(
            f"    {line}"
            for line in classification_report(
                holdout["label"], predicted, target_names=["reached 2B", "did not"], zero_division=0
            ).splitlines()
        )
    )

    # --- coefficients --------------------------------------------------------
    #
    # Fitted on everything, which is the model that ships. The metrics above come
    # from folds that never saw their own test rows.
    final_model, final_scaler, final_means = fit(frame, features)

    rule("Coefficients (standardised units, final model)")
    print(f"  {'intercept':22}{final_model.intercept_[0]:>9.4f}")
    order = np.argsort(-np.abs(final_model.coef_[0]))
    for index in order:
        coefficient = final_model.coef_[0][index]
        direction = "raises risk" if coefficient > 0 else "lowers risk"
        print(f"  {features[index]:22}{coefficient:>9.4f}   {direction}")

    # --- verdict -------------------------------------------------------------
    rule("Verdict")
    better = None
    if cv_auc and ho_auc:
        better = cv_auc[0] > cv_auc[1] and ho_auc[0] >= ho_auc[1]
        print(f"  pooled CV   model {cv_auc[0]:.3f} vs heuristic {cv_auc[1]:.3f}")
        print(f"  held-out    model {ho_auc[0]:.3f} vs heuristic {ho_auc[1]:.3f}")
        if better:
            print("\n  The model ranks better than the phase 7 heuristic on data it never saw.")
            print("  Serve the model; keep the heuristic as the fallback when model.json is absent.")
        else:
            print("\n  The model does NOT rank better than the phase 7 heuristic.")
            print("  Per the brief, KEEP THE HEURISTIC. A worse model dressed as machine")
            print("  learning is worse than an honest hand-weighted score.")
    print(f"\n  Sample size: {len(frame)} rows, {int(frame['label'].sum())} positives,")
    print(f"  {frame['gstin'].nunique()} suppliers, {len(periods)} label periods. This is small.")
    print("  Treat every figure above as indicative, not established.")

    if args.no_write:
        return

    payload = {
        "intercept": float(final_model.intercept_[0]),
        "coefficients": [float(value) for value in final_model.coef_[0]],
        "featureNames": features,
        "means": [float(final_scaler.mean_[i]) for i in range(len(features))],
        "stds": [float(scale) for scale in final_scaler.scale_],
        # Everything below is documentation that travels with the weights, so a
        # reader of model.json is never left guessing what it was fitted on.
        "meta": {
            "trainedOn": "synthetic fixtures from tools/generate-fixtures.js",
            "rows": int(len(frame)),
            "positives": int(frame["label"].sum()),
            "suppliers": int(frame["gstin"].nunique()),
            "labelPeriods": periods,
            "droppedFeatures": {
                name: {"reason": why, "constantValue": constant}
                for name, why, constant in dropped
            },
            # Imputation values for a feature that is missing at serve time.
            # Standardising the mean gives 0, so an unknown contributes nothing.
            "imputeMeans": {name: float(final_means[name]) for name in features},
            "bands": {"low": BAND_LOW, "high": BAND_HIGH},
            "holdoutPeriod": HOLDOUT_PERIOD,
            "metrics": {
                "cvRocAuc": None if not cv_auc else round(cv_auc[0], 4),
                "cvRocAucHeuristic": None if not cv_auc else round(cv_auc[1], 4),
                "holdoutRocAuc": None if not ho_auc else round(ho_auc[0], 4),
                "holdoutRocAucHeuristic": None if not ho_auc else round(ho_auc[1], 4),
                "cvAveragePrecision": None if not cv_ap else round(cv_ap[0], 4),
                "cvAveragePrecisionHeuristic": None if not cv_ap else round(cv_ap[1], 4),
            },
            "beatsHeuristic": better,
        },
    }
    pathlib.Path(args.out).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf8")
    print(f"\nwrote {args.out}")


if __name__ == "__main__":
    main()
